<?php
// This script and data application were generated by AppGini 5.62
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/courses_catalog.php");
	include("$currDir/courses_catalog_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('courses_catalog');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "courses_catalog";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`courses_catalog`.`cat_id`" => "cat_id",
		"`courses_catalog`.`course_code`" => "course_code",
		"`courses_catalog`.`course_name`" => "course_name",
		"if(CHAR_LENGTH(`courses_catalog`.`course_summary`)>400, concat(left(`courses_catalog`.`course_summary`,400),' ...'), `courses_catalog`.`course_summary`)" => "course_summary",
		"`courses_catalog`.`course_contents`" => "course_contents",
		"`courses_catalog`.`notes`" => "notes"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`courses_catalog`.`cat_id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`courses_catalog`.`cat_id`" => "cat_id",
		"`courses_catalog`.`course_code`" => "course_code",
		"`courses_catalog`.`course_name`" => "course_name",
		"`courses_catalog`.`course_summary`" => "course_summary",
		"`courses_catalog`.`course_contents`" => "course_contents",
		"`courses_catalog`.`notes`" => "notes"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`courses_catalog`.`cat_id`" => "ID",
		"`courses_catalog`.`course_code`" => "Course code",
		"`courses_catalog`.`course_name`" => "Course name",
		"`courses_catalog`.`course_summary`" => "Course summary",
		"`courses_catalog`.`course_contents`" => "Course contents",
		"`courses_catalog`.`notes`" => "Notes"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`courses_catalog`.`cat_id`" => "cat_id",
		"`courses_catalog`.`course_code`" => "course_code",
		"`courses_catalog`.`course_name`" => "course_name",
		"`courses_catalog`.`course_summary`" => "Course summary",
		"`courses_catalog`.`course_contents`" => "course_contents",
		"`courses_catalog`.`notes`" => "notes"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`courses_catalog` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "courses_catalog_view.php";
	$x->RedirectAfterInsert = "courses_catalog_view.php?SelectedID=#ID#";
	$x->TableTitle = "Courses catalog";
	$x->TableIcon = "resources/table_icons/application_from_storage.png";
	$x->PrimaryKey = "`courses_catalog`.`cat_id`";

	$x->ColWidth   = array(  70, 200, 300, 300);
	$x->ColCaption = array("Course code", "Course name", "Course summary", "Notes");
	$x->ColFieldName = array('course_code', 'course_name', 'course_summary', 'notes');
	$x->ColNumber  = array(2, 3, 4, 6);

	// template paths below are based on the app main directory
	$x->Template = 'templates/courses_catalog_templateTV.html';
	$x->SelectedTemplate = 'templates/courses_catalog_templateTVS.html';
	$x->TemplateDV = 'templates/courses_catalog_templateDV.html';
	$x->TemplateDVP = 'templates/courses_catalog_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `courses_catalog`.`cat_id`=membership_userrecords.pkValue and membership_userrecords.tableName='courses_catalog' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `courses_catalog`.`cat_id`=membership_userrecords.pkValue and membership_userrecords.tableName='courses_catalog' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`courses_catalog`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: courses_catalog_init
	$render=TRUE;
	if(function_exists('courses_catalog_init')){
		$args=array();
		$render=courses_catalog_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: courses_catalog_header
	$headerCode='';
	if(function_exists('courses_catalog_header')){
		$args=array();
		$headerCode=courses_catalog_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: courses_catalog_footer
	$footerCode='';
	if(function_exists('courses_catalog_footer')){
		$args=array();
		$footerCode=courses_catalog_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>