<?php
// This script and data application were generated by AppGini 5.62
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/enrollment.php");
	include("$currDir/enrollment_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('enrollment');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "enrollment";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`enrollment`.`rec_id`" => "rec_id",
		"IF(    CHAR_LENGTH(`students1`.`student_name`), CONCAT_WS('',   `students1`.`student_name`), '') /* Student */" => "stud_id",
		"IF(    CHAR_LENGTH(`courses_catalog1`.`course_name`), CONCAT_WS('',   `courses_catalog1`.`course_name`, '  '), '') /* Course */" => "course_id",
		"`enrollment`.`score`" => "score",
		"`enrollment`.`notes`" => "notes",
		"`enrollment`.`certificate_notes`" => "certificate_notes"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`enrollment`.`rec_id`',
		2 => '`students1`.`student_name`',
		3 => '`courses_catalog1`.`course_name`',
		4 => 4,
		5 => 5,
		6 => 6
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`enrollment`.`rec_id`" => "rec_id",
		"IF(    CHAR_LENGTH(`students1`.`student_name`), CONCAT_WS('',   `students1`.`student_name`), '') /* Student */" => "stud_id",
		"IF(    CHAR_LENGTH(`courses_catalog1`.`course_name`), CONCAT_WS('',   `courses_catalog1`.`course_name`, '  '), '') /* Course */" => "course_id",
		"`enrollment`.`score`" => "score",
		"`enrollment`.`notes`" => "notes",
		"`enrollment`.`certificate_notes`" => "certificate_notes"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`enrollment`.`rec_id`" => "Record ID",
		"IF(    CHAR_LENGTH(`students1`.`student_name`), CONCAT_WS('',   `students1`.`student_name`), '') /* Student */" => "Student",
		"IF(    CHAR_LENGTH(`courses_catalog1`.`course_name`), CONCAT_WS('',   `courses_catalog1`.`course_name`, '  '), '') /* Course */" => "Course",
		"`enrollment`.`score`" => "Score",
		"`enrollment`.`notes`" => "Comments",
		"`enrollment`.`certificate_notes`" => "Certificate notes"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`enrollment`.`rec_id`" => "rec_id",
		"IF(    CHAR_LENGTH(`students1`.`student_name`), CONCAT_WS('',   `students1`.`student_name`), '') /* Student */" => "stud_id",
		"IF(    CHAR_LENGTH(`courses_catalog1`.`course_name`), CONCAT_WS('',   `courses_catalog1`.`course_name`, '  '), '') /* Course */" => "course_id",
		"`enrollment`.`score`" => "score",
		"`enrollment`.`notes`" => "notes",
		"`enrollment`.`certificate_notes`" => "certificate_notes"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'stud_id' => 'Student', 'course_id' => 'Course');

	$x->QueryFrom = "`enrollment` LEFT JOIN `students` as students1 ON `students1`.`student_id`=`enrollment`.`stud_id` LEFT JOIN `courses` as courses1 ON `courses1`.`course_id`=`enrollment`.`course_id` LEFT JOIN `courses_catalog` as courses_catalog1 ON `courses_catalog1`.`cat_id`=`courses1`.`course_name` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "enrollment_view.php";
	$x->RedirectAfterInsert = "enrollment_view.php";
	$x->TableTitle = "Student Enrollments";
	$x->TableIcon = "resources/table_icons/data_chooser.png";
	$x->PrimaryKey = "`enrollment`.`rec_id`";

	$x->ColWidth   = array(  200, 200, 100, 200);
	$x->ColCaption = array("Student", "Course", "Score", "Comments");
	$x->ColFieldName = array('stud_id', 'course_id', 'score', 'notes');
	$x->ColNumber  = array(2, 3, 4, 5);

	// template paths below are based on the app main directory
	$x->Template = 'templates/enrollment_templateTV.html';
	$x->SelectedTemplate = 'templates/enrollment_templateTVS.html';
	$x->TemplateDV = 'templates/enrollment_templateDV.html';
	$x->TemplateDVP = 'templates/enrollment_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `enrollment`.`rec_id`=membership_userrecords.pkValue and membership_userrecords.tableName='enrollment' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `enrollment`.`rec_id`=membership_userrecords.pkValue and membership_userrecords.tableName='enrollment' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`enrollment`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: enrollment_init
	$render=TRUE;
	if(function_exists('enrollment_init')){
		$args=array();
		$render=enrollment_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: enrollment_header
	$headerCode='';
	if(function_exists('enrollment_header')){
		$args=array();
		$headerCode=enrollment_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: enrollment_footer
	$footerCode='';
	if(function_exists('enrollment_footer')){
		$args=array();
		$footerCode=enrollment_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>