<?php
// This script and data application were generated by AppGini 5.62
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/instructors.php");
	include("$currDir/instructors_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('instructors');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "instructors";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`instructors`.`inst_id`" => "inst_id",
		"`instructors`.`inst_name`" => "inst_name",
		"`instructors`.`email`" => "email",
		"`instructors`.`phone`" => "phone",
		"concat('<img src=\"', if(`instructors`.`fulltime`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "fulltime",
		"`instructors`.`photo`" => "photo",
		"`instructors`.`notes`" => "notes"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`instructors`.`inst_id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`instructors`.`inst_id`" => "inst_id",
		"`instructors`.`inst_name`" => "inst_name",
		"`instructors`.`email`" => "email",
		"`instructors`.`phone`" => "phone",
		"`instructors`.`fulltime`" => "fulltime",
		"`instructors`.`photo`" => "photo",
		"`instructors`.`notes`" => "notes"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`instructors`.`inst_id`" => "Instructor ID",
		"`instructors`.`inst_name`" => "Instructor",
		"`instructors`.`email`" => "email",
		"`instructors`.`phone`" => "Phone",
		"`instructors`.`fulltime`" => "Full Time?",
		"`instructors`.`notes`" => "Notes"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`instructors`.`inst_id`" => "inst_id",
		"`instructors`.`inst_name`" => "inst_name",
		"`instructors`.`email`" => "email",
		"`instructors`.`phone`" => "phone",
		"concat('<img src=\"', if(`instructors`.`fulltime`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "fulltime",
		"`instructors`.`notes`" => "notes"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`instructors` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "instructors_view.php";
	$x->RedirectAfterInsert = "instructors_view.php";
	$x->TableTitle = "Instructors Data";
	$x->TableIcon = "resources/table_icons/administrator.png";
	$x->PrimaryKey = "`instructors`.`inst_id`";

	$x->ColWidth   = array(  200, 50, 125, 60, 150);
	$x->ColCaption = array("Instructor", "email", "Phone", "Full Time?", "Instructor photo");
	$x->ColFieldName = array('inst_name', 'email', 'phone', 'fulltime', 'photo');
	$x->ColNumber  = array(2, 3, 4, 5, 6);

	// template paths below are based on the app main directory
	$x->Template = 'templates/instructors_templateTV.html';
	$x->SelectedTemplate = 'templates/instructors_templateTVS.html';
	$x->TemplateDV = 'templates/instructors_templateDV.html';
	$x->TemplateDVP = 'templates/instructors_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `instructors`.`inst_id`=membership_userrecords.pkValue and membership_userrecords.tableName='instructors' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `instructors`.`inst_id`=membership_userrecords.pkValue and membership_userrecords.tableName='instructors' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`instructors`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: instructors_init
	$render=TRUE;
	if(function_exists('instructors_init')){
		$args=array();
		$render=instructors_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: instructors_header
	$headerCode='';
	if(function_exists('instructors_header')){
		$args=array();
		$headerCode=instructors_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: instructors_footer
	$footerCode='';
	if(function_exists('instructors_footer')){
		$args=array();
		$footerCode=instructors_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>