<?php
// This script and data application were generated by AppGini 5.62
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/labs.php");
	include("$currDir/labs_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('labs');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "labs";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`labs`.`lab_id`" => "lab_id",
		"`labs`.`lab_code`" => "lab_code",
		"`labs`.`capacity`" => "capacity",
		"`labs`.`notes`" => "notes"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`labs`.`lab_id`',
		2 => 2,
		3 => '`labs`.`capacity`',
		4 => 4
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`labs`.`lab_id`" => "lab_id",
		"`labs`.`lab_code`" => "lab_code",
		"`labs`.`capacity`" => "capacity",
		"`labs`.`notes`" => "notes"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`labs`.`lab_id`" => "Lab ID",
		"`labs`.`lab_code`" => "Lab code",
		"`labs`.`capacity`" => "Capacity",
		"`labs`.`notes`" => "Notes"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`labs`.`lab_id`" => "lab_id",
		"`labs`.`lab_code`" => "lab_code",
		"`labs`.`capacity`" => "capacity",
		"`labs`.`notes`" => "notes"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`labs` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "labs_view.php";
	$x->RedirectAfterInsert = "labs_view.php";
	$x->TableTitle = "Labs";
	$x->TableIcon = "resources/table_icons/color_swatch.png";
	$x->PrimaryKey = "`labs`.`lab_id`";

	$x->ColWidth   = array(  100, 100, 300);
	$x->ColCaption = array("Lab code", "Capacity", "Notes");
	$x->ColFieldName = array('lab_code', 'capacity', 'notes');
	$x->ColNumber  = array(2, 3, 4);

	// template paths below are based on the app main directory
	$x->Template = 'templates/labs_templateTV.html';
	$x->SelectedTemplate = 'templates/labs_templateTVS.html';
	$x->TemplateDV = 'templates/labs_templateDV.html';
	$x->TemplateDVP = 'templates/labs_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `labs`.`lab_id`=membership_userrecords.pkValue and membership_userrecords.tableName='labs' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `labs`.`lab_id`=membership_userrecords.pkValue and membership_userrecords.tableName='labs' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`labs`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: labs_init
	$render=TRUE;
	if(function_exists('labs_init')){
		$args=array();
		$render=labs_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: labs_header
	$headerCode='';
	if(function_exists('labs_header')){
		$args=array();
		$headerCode=labs_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: labs_footer
	$footerCode='';
	if(function_exists('labs_footer')){
		$args=array();
		$footerCode=labs_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>